function workflows = select_workflows_gui(task_workflows, visual_passive_workflows, audio_passive_workflows)

    % 输出
    workflows = cell(3,1);

    % 主窗口
    fig = figure( ...
        'Name', 'Select workflows', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Resize', 'off', ...
        'Position', [300 200 1100 500], ...
        'CloseRequestFcn', @onCancel);

    % 三列面板
    p1 = uipanel(fig, 'Title', 'Task workflows', 'Position', [0.03 0.15 0.30 0.80]);
    p2 = uipanel(fig, 'Title', 'Visual passive',  'Position', [0.35 0.15 0.30 0.80]);
    p3 = uipanel(fig, 'Title', 'Audio passive',   'Position', [0.67 0.15 0.30 0.80]);

    % 列表框
    hTask = uicontrol(p1, 'Style', 'listbox', ...
        'String', task_workflows, ...
        'Units', 'normalized', ...
        'Position', [0.05 0.05 0.90 0.90], ...
        'Max', 2, ...   % 多选
        'Min', 0, ...
        'Value', 1, ...
        'FontSize', 11);

    hVisual = uicontrol(p2, 'Style', 'listbox', ...
        'String', visual_passive_workflows, ...
        'Units', 'normalized', ...
        'Position', [0.05 0.05 0.90 0.90], ...
        'Max', 1, ...   % 单选
        'Min', 0, ...
        'Value', 1, ...
        'FontSize', 11);

    hAudio = uicontrol(p3, 'Style', 'listbox', ...
        'String', audio_passive_workflows, ...
        'Units', 'normalized', ...
        'Position', [0.05 0.05 0.90 0.90], ...
        'Max', 1, ...   % 单选
        'Min', 0, ...
        'Value', 1, ...
        'FontSize', 11);

    % 确定/取消按钮
    hOK = uicontrol(fig, 'Style', 'pushbutton', ...
        'String', '确定', ...
        'Units', 'normalized', ...
        'Position', [0.40 0.03 0.10 0.07], ...
        'FontSize', 11, ...
        'Callback', @onOK);

    uicontrol(fig, 'Style', 'pushbutton', ...
        'String', '取消', ...
        'Units', 'normalized', ...
        'Position', [0.52 0.03 0.10 0.07], ...
        'FontSize', 11, ...
        'Callback', @onCancel);

    % 保存句柄
    handles.task = hTask;
    handles.visual = hVisual;
    handles.audio = hAudio;
    handles.result = [];
    guidata(fig, handles);

    uiwait(fig);

    % 如果窗口被取消，返回空
    if ishandle(fig)
        handles = guidata(fig);
        if isempty(handles.result)
            workflows = {};
        else
            workflows = handles.result;
        end
        delete(fig);
    end

    % -------- 回调函数 --------
    function onOK(~,~)
        handles = guidata(fig);

        task_idx   = get(handles.task,   'Value');
        visual_idx = get(handles.visual, 'Value');
        audio_idx  = get(handles.audio,  'Value');

        % 取出选择结果，保持和你原来一致：都是 cell
        workflows{1,1} = task_workflows(task_idx);
        workflows{2,1} = visual_passive_workflows(visual_idx);
        workflows{3,1} = audio_passive_workflows(audio_idx);

        handles.result = workflows;
        guidata(fig, handles);

        uiresume(fig);
    end

    function onCancel(~,~)
        handles = guidata(fig);
        handles.result = {};
        guidata(fig, handles);
        uiresume(fig);
    end
end