clear 

% Output root (script will create per-ID subfolders)
OUTPUT_ROOT = 'D:\Data process\project_cross_model\face_data\sleap\track_data\pupil';
MODEL_DIRS = { 'D:\Data process\project_cross_model\face_data\sleap\pupil\251117_190801.centroid.n=625',...
               'D:\Data process\project_cross_model\face_data\sleap\pupil\251117_212458.centered_instance.n=625' };

% OUTPUT_ROOT = 'D:\Data process\project_cross_model\face_data\sleap\track_data\nose_cheek';
% MODEL_DIRS = { 'D:\Data process\project_cross_model\face_data\sleap\nose_cheek\models\260310_142421.centroid.n=376',...
%                'D:\Data process\project_cross_model\face_data\sleap\nose_cheek\models\260310_145117.centered_instance.n=376' };
% 

animals =     { 'DS007','DS010','AP019','AP021','DS011','AP022',...
    'DS000','DS004','DS014','DS015','DS016'};
all_workflow={ ['stim_wheel_right_stage1$|' ...
    'stim_wheel_right_stage2$|' ...
    'stim_wheel_right_stage1_opacity$|' ...
    'stim_wheel_right_stage2_opacity$|' ...
    'stim_wheel_right_stage1_angle$|' ...
    'stim_wheel_right_stage2_angle$|' ...
    'stim_wheel_right_stage2_angle_size60$|' ...
    'stim_wheel_right_stage1_size_up$|' ...
    'stim_wheel_right_stage2_size_up$|' ...
    'stim_wheel_right_stage1_audio_volume*$|'...
    'stim_wheel_right_stage2_audio_volume*$|' ...
    'stim_wheel_right_stage1_audio_frequency$|' ...
    'stim_wheel_right_stage2_audio_frequency$|' ...
    'stim_wheel_right_frequency_stage2_mixed_VA$|' ...
    'stim_wheel_right_stage2_mixed_VA$'],...
    'lcr_passive','hml_passive_audio'};

for curr_animal=1:length(animals)

    animal=animals{curr_animal};

    outDirID = fullfile(OUTPUT_ROOT, animal);
    if ~exist(outDirID, 'dir'), mkdir(outDirID); end

    for curr_workflow=2:3

        recordings = plab.find_recordings(animal,[],all_workflow{curr_workflow});
        for curr_recording =1:length(recordings)

            rec_day = recordings(curr_recording).day;

            [~,index_real]=max( cellfun(@(rt) ...
                numel(load( ...
                plab.locations.filename('server', animal, rec_day, rt, 'timelite.mat'), ...
                'timestamps').timestamps), ...
                recordings(curr_recording).recording));
            rec_time = recordings(curr_recording).recording{index_real};
            workflow=recordings(curr_recording).workflow{index_real};
            mousecam_fn = plab.locations.filename('server',animal,rec_day,rec_time,'mousecam','mousecam.mj2');

           
            outBase = sprintf('%s_%s_Recording_%s_%s', animal, rec_day, rec_time, 'mousecam');
            outSLP = fullfile(outDirID, [outBase, '.pred.slp']);
            outH5  = fullfile(outDirID, [outBase, '.analysis.h5']);
            if isfile(outSLP)
                fprintf('File exists, skip %s.\n', outSLP);
                continue;   % 跳过本次循环
            end

            fprintf('\n Processing: %s  %s    %s\n', animal, workflow,rec_day);

            ds.sleap_inference(MODEL_DIRS,mousecam_fn,outSLP,outH5)

        end
    end
end

